### ISSUE TITLE
Scaling Factor isn't appended when taking a screenshot from Terminal

### ISSUE THREAD

**Issue by cassidyjames** [elementary/screenshot#107]
Reported by @peteruithoven at https://github.com/elementary/screenshot/issues/68#issuecomment-427176616

>It looks like the scaling factor isn't added when using the command line tool. 

We probably want to check for something other than the current window's current scale factor, as the window obviously isn't open when a screenshot is invoked from the command line.

**Comment by peteruithoven** [comment]
I think the plan is to have gala handle this in the future: https://github.com/elementary/screenshot/issues/103
So I'm not sure this should we fixed in Screenshot.

**Comment by danirabbit** [comment]
Seems to be fixed now
