### ISSUE TITLE
Screenshot tool only captures a quater of the screen when 2x scaling is applied

### ISSUE THREAD

**Issue by yamnikov-oleg** [elementary/screenshot#115]
Reproduction steps:

1. Set scaling factor to 2x in display settings.
2. Launch screenshot tool and make full-screen screenshot

The screenshot tool only captures the top left quarter of the screen. [Example](https://i.imgur.com/JrKslnY.jpg) (my screen is 3072x1728, the screenshot is 1536x864).

I'm not sure, if it's relevant, but my display is also scaled with xrandr: `xrandr --output eDP1 --fb 3072x1728 --panning 3072x1728 --scale 1.6x1.6 --dpi 192`.

**Comment by cassidyjames** [comment]
@yamnikov-oleg this is not reproducible using built-in HiDPI support in Juno. I imagine the xrandr scaling is what's causing an issue here.
