### ISSUE TITLE
Delay is not respected after opening the window and not modifying it

### ISSUE THREAD

**Issue by cassidyjames** [elementary/screenshot#121]
## To reproduce

1. Open Screenshot
2. Set a non-zero delay (i.e. 3 seconds)
3. Close screenshot
4. Re-open screenshot
5. Take a screenshot without modifying the delay

## Expected

The delay (i.e. 3 seconds) is respected.

## Actual

The delay is listed, but the screenshot is immediate.

**Comment by peteruithoven** [comment]
I think this should have been fixed with: https://github.com/elementary/screenshot/pull/119
Did you try the latest master?

**Comment by cassidyjames** [comment]
@peteruithoven ah I could have been running an old version. I am not seeing the issue on my desktop but was seeing it on my laptop. I'll give updated master a try there and re-open if it's still an issue.
