### ISSUE TITLE
Failure to compile SourceTreePlugin.vala

### ISSUE THREAD

**Issue by arruah** [elementary/screenshot#123]
../src/ScreenshotWindow.vala:78.56-78.81: error: The name `STYLE_CLASS_ACCENT' does not exist in the context of `Granite'
            radio_grid.get_style_context ().add_class (Granite.STYLE_CLASS_ACCENT);
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 20 warning(s)
[6/11] Compiling C object 'io.elementary.screenshot-tool@exe/meson-generated_.._screenshot-icon-resources.c.o'.
ninja: build stopped: subcommand failed.

**Comment by tintou** [comment]
You need Granite 5.0 to build it
