### ISSUE TITLE
Copy area to clipboard no longer works

### ISSUE THREAD

**Issue by GammaGames** [elementary/screenshot#125]
I have vanilla keyboard shortcuts:
![image](https://user-images.githubusercontent.com/7832163/53646986-c33d9800-3bf9-11e9-9d98-54e72b0d8a90.png)

The Shift + Ctrl + Print shortcut brings up the interface to copy the shortcut, but it fails to be copied. `/var/log/syslog` reports:
```
Mar  1 08:13:57 jl-eos gsd-media-keys[2534]: Failed to save a screenshot: GDBus.Error:org.freedesktop.DBus.Error.Failed: Failed to save image
```

Using the tool manually and picking the "Copy to Clipboard" button after selecting an area works as expected.

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is the second duplicate today of: https://github.com/elementary/gala/issues/474

**Comment by GammaGames** [comment]
Ah, I didn't realize it was a gala issue. I didn't think I had seen any screenshot-tool updates so I should have guessed. Thank you!

**Comment by peteruithoven** [comment]
I understand it's quite difficult to understand what aspect of the os is responsible for what, took me ages. If you're unsure I'd recommend searching of issues in the whole elementary org.
