### ISSUE TITLE
Ctrl+Shipt+PrtScrn not working

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/screenshot#128]
Trying to screenshot a aregion of the screen with `Ctrl+Shipt+PrtScrn` does not work. The animation and sound effect appear, but no file is generated.

**Comment by peteruithoven** [comment]
`Ctrl+Shipt+PrtScrn`, by default will copy the screenshot to clipboard? Please check your keyboard shortcuts. 

Screenshots triggered by the keyboard shortcut are actually taken by Gala.

**Comment by Gabriel-p** [comment]
Sorry I got confused with `Shipt+PrtScrn` which produces the file. My bad.
