### ISSUE TITLE
Implement Screenshot portal

### ISSUE THREAD

**Issue by cassidyjames** [elementary/screenshot#140]
Looks like it's implemented in xdg-desktop-portal but it's super GNOME-y. We'll want the UI to be effectively the same as the main mode of the app.

**Comment by Marukesu** [comment]
@danrabbit should we drop the screenshot app when implementing the portal? it's already broken in GNOME as reported in #238, since `org.gnome.Shell.Screenshot` is now an private interface (i don't know about others desktops that use the shell interface besides us and GNOME).

**Comment by danrabbit** [comment]
@Marukesu Yeah we should probably implement our own private interface instead of using the `org.gnome.Shell.Screenshot` namespace, but I'm not sure what you mean about dropping the screenshot app? I think we'd want to implement the portal here in the screenshot app since we have no screenshot UI in gala

**Comment by Marukesu** [comment]
i mean, the portal in `interactive` mode will be the same of the screenshot app. So instead of having two binaries doing the same thing, have only the portal.

**Comment by danrabbit** [comment]
@Marukesu ah as in you want to move this interface to elementary/portals?

**Comment by Marukesu** [comment]
We can keep it in this repo, if desired, but what i don't want is having both `io.elementary.screenshot` and `io.elementay.screenshot.xdg-desktop-portal` applications when the diference is one exposing an CLI interface and the other an DBus one.

**Comment by phase1geo** [comment]
As the developer of Annotator (which includes a feature for taking a screenshot to be edited within the application), it would be nice if the priority of this feature could be bumped up.  Looks like it has been opened for a long time now.  I have heard in the May release notes that the background portal was going to get some support, but I haven't heard anything about the screenshot portal.
