### ISSUE TITLE
Provide A Screenshot Icon For AppCenter

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/screenshot#144]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

Screenshot is one of three native default apps that do not yet display their own icons in AppCenter. This looks a bit inconsistent for the wonderful desktop. Code and Music already have an issue for it. Music even already has a PR with a possible solution:
https://github.com/elementary/music/pull/511
I hope that this is a little fix that you can realize for Hera! 

### Screenshots or screen recordings

See https://github.com/elementary/code/issues/621 and https://github.com/elementary/music/issues/334 for reference.

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by ryonakano** [comment]
Closing since the issue seems to be gone on Hera
