### ISSUE TITLE
Active menus disable screenshot shortcut

### ISSUE THREAD

**Issue by joe247** [elementary/screenshot#152]
- [X] I have searched open and closed issues for duplicates.

## The bug
An active context menu (elementary-styled) disables screenshot shortcut. Neither the <kbd>PrntScr</kbd> nor <kbd>Shift</kbd>+<kbd>PrntScr</kbd> work when a system context menu is active. <br>_**A Firefox context menu does not behave this way (differs from #130 & [#500](https://github.com/elementary/gala/issues/500) here).**_

Screenshot (using the app & delay timer):
![Screenshot from 2020-01-18 20 12 34](https://user-images.githubusercontent.com/38415384/72665517-eac66a80-3a2e-11ea-811b-d9c56c46af7b.png)
Screenshot (using <kbd>PrntScr</kbd>):
![Screenshot from 2020-01-18 20-13-21](https://user-images.githubusercontent.com/38415384/72665539-311bc980-3a2f-11ea-8f77-f029eb9339b5.png)
This happens across elementary apps including `code`, `files`, `terminal`, `calendar` (in the space to add a new event-comments).

### To Reproduce
Steps to reproduce the behaviour:
1. Open any elementary app
2. Right click to show context menu (where possible)
3. Press <kbd>PrntScr</kbd> or <kbd>Shift</kbd>+<kbd>PrntScr</kbd>
4. It does not take screenshot.

### Expected behaviour
A simple screenshot is taken as usual.

## Platform Information
```java
         eeeeeeeeeeeeeeeee            joe@eOS 
      eeeeeeeeeeeeeeeeeeeeeee         ------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 5.1 Hera x86_64 
  eeee   eeeee       eee     eeee     Host: Dell System XPS L502X 
 eeee   eeee          eee     eeee    Kernel: 5.3.0-26-generic 
eee    eee            eee       eee   Uptime: 1 hour, 7 mins 
eee   eee            eee        eee   Packages: 1920 
ee    eee           eeee       eeee   Shell: bash 4.4.20 
ee    eee         eeeee      eeeeee   Resolution: 1366x768 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: Elementary [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: Elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: io.elementary.t 
    eeeee                 eeeee       CPU: Intel i5-2410M (4) @ 2.900GHz 
      eeeeeee         eeeeeee         GPU: NVIDIA GeForce GT 525M 
         eeeeeeeeeeeeeeeee            GPU: Intel 2nd Generation Core Processor Family 
                                      Memory: 2051MiB / 11875MiB 
```
- [X] I'm using the latest released stable version

**Comment by Exalm** [comment]
That's a well-known X11 limitation: https://unix.stackexchange.com/questions/347337/why-keyboard-shortcuts-do-not-work-when-a-sub-menu-is-activated

This also isn't specific to Screenshot, it happens with any hotkeys.
