### ISSUE TITLE
Using the shortcuts or the GUI generates differents folders

### ISSUE THREAD

**Issue by efdiloreto** [elementary/screenshot#157]
## Prerequisites
- [ x] I have searched open and closed issues for duplicates.

## Describe the bug
I'm using eOS Hera 5.1.3 in Spanish language.

When I take an screenshot using the GUI, a folder named "Captura de Pantalla" is created in the "Images" folder. But, when I take an screenshot using the shortcuts, another folder is created named "Capturas de Pantalla". So, I have two folder with screenshots images.

![Captura de pantalla de 2020-04-24 13-17-20](https://user-images.githubusercontent.com/23631382/80234128-fb8a0c00-862d-11ea-8227-cf7b97cdd19e.png)

**Comment by danrabbit** [comment]
Fixed by #147
