### ISSUE TITLE
Black screen area grabbing

### ISSUE THREAD

**Issue by bphd** [elementary/screenshot#158]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

____________________

All is in the title
I guess that with Pantheon it works fine, but i'm on OpenBox and I experience a total black screen the time to grab an area (I guess thats originally the shadow produced by the GUI in this event)
Is there a way to remove this function or installing what he needs to generate fine the shadow?

**Comment by danrabbit** [comment]
Screenshot now relies on the Shell to implement the screenshot interface, so my guess is that it no longer works with OpenBox at all

**Comment by bphd** [comment]
For me it works, it's just annoying that you cannot see what you're grabbing

**Comment by Exalm** [comment]
It stopped supporting it a few minutes ago.

Anyway, to answer your question, the window selection frame is half-transparent and openbox doesn't support that.

**Comment by bphd** [comment]
Okay so it should be the last update on my distro.

Unless they linked to the GitHub so the update will breaks compatibility and the package will be deleted over time
