### ISSUE TITLE
[odin-beta] `io.elementary.screenshot` put up for `apt-get autoremove` after `apt-get dist-upgrade`

### ISSUE THREAD

**Issue by GlasierXplor** [elementary/screenshot#211]
## What Happened

After installation of the Odin Beta, I ran `sudo apt-get update` and `sudo apt-get dist-upgrade` to install all updates that were available (I understand you prefer that we install updates using AppCenter).

Immediately after `sudo apt-get dist-upgrade`, `io.elementary.screenshot` will be put up for `autoremove`.

I allowed `apt-get` to remove it. This removes the "Screenshot" icon from the Application Menu.
![Screenshot from 2021-05-09 23-19-41](https://user-images.githubusercontent.com/25283178/117577605-11754c80-b11d-11eb-8d4d-d0261cb5db4e.png)

## Expected Behavior

I am unsure if this is expected behaviour, but I find it odd and would like to bring it up _just in case_.

## Steps to Reproduce

1. Install the public beta ISO.
2. After installation, pull up a terminal and run `sudo apt-get update`.
3. Subsequently run `sudo apt-get dist-upgrade` to perform a "full system upgrade".
    - Notice that `io.elementary.screenshot` is one of the packages being updated.
4. Then run `sudo apt-get autoremove`. `apt-get` will prompt for confirmation to remove packages.
    - `io.elementary.screenshot` will be offered to be `autoremove`d

### Logs

N.A.

## Platform Information

elementaryOS 6.0 Public Beta (`elementaryos-6.0-daily.20210430.iso`)
`io.elementary.screenshot` update as of 09 May 2021

**Comment by danrabbit** [comment]
This is expected. We no longer ship screenshot as a debian package, instead it is shipped as a flatpak. You can manually install the flatpak version yourself from either AppCenter or Terminal
