### ISSUE TITLE
Screenshots to clipboard don't paste into many apps like Web, etc. (ctrl+prnt, ctrl+shift+prnt, ctrl+alt+prnt)

### ISSUE THREAD

**Issue by Schykle** [elementary/screenshot#224]
## What Happened

Screenshots to clipboard will often not paste into websites or apps. Not sure if a Flatpak issue or not, but I don't see an explicit permission for access to the clipboard anywhere for apps, so I imagine it's not a permission issue.

## Expected Behavior

Any image/screenshot to the clipboard should be paste-able to any field.

## Steps to Reproduce

1. Take a screenshot to the clipboard via `Ctrl`+`Prnt`, etc.
2. Attempt to paste into a site like Twitter, etc in Web
3. Paste does not occur.

## Platform Information
elementary OS 6.0 - Fully updated as of 2021-08-15

**Comment by mikerosas** [comment]
I confirm it doesn't work trough keyboard shortcut, the GUI is an extra step tho. On Ubuntu the screenshot shorcuts are working ok as it should.

**Comment by cheryllium** [comment]
I'm having this problem on Elementary OS Horus. Screenshot will not paste into Element desktop application. Screenshot does paste successfully into Discord for Firefox.

**Comment by ChillingSilence** [comment]
Can confirm I'm having the same issue on multiple machines , version 6.0.4 on Elementary OS 7.1.

To reproduce:
* Open screenshot
* "Select area to grab"
* Take screenshot
* Click and drag over are and choose "copy to clipboard"
* Attempt to paste into another app such as Github

It's often less than a 50% success rate at doing this, incredibly frustrating. Doesn't matter if I'm trying to use Ctrl + V as shown in the video below (The pause after deleting the asterisk is me trying to use hotkeys) or right-clicking and choosing "Paste".

https://github.com/elementary/screenshot/assets/162461/6834197d-b094-4775-9357-27383a43f36a

Any feedback or suggestions would be appreciated. If I can get more logs on this for you, please let me know how.

**Comment by samueltuyizere** [comment]
I think this broke the app for me after updating it yesterday.
If i open the app and take a screenshot, the screenshot is copied to the clipboard and then the app closes itself r disappears. no longer gives me the option to pick if i want to copy the screenshot to clipboard or save it to files.
Also, when I open the app, it always defaults to the screen-shooting the whole window instead of the previously selected/used option.

**Comment by DieterPi** [comment]
> I think this broke the app for me after updating it yesterday. If i open the app and take a screenshot, the screenshot is copied to the clipboard and then the app closes itself r disappears. no longer gives me the option to pick if i want to copy the screenshot to clipboard or save it to files. Also, when I open the app, it always defaults to the screen-shooting the whole window instead of the previously selected/used option.

Same problem here!

**Comment by guiphc** [comment]
it is complete broke for me, fresh install most recent, and is unable to select anything or even save at clipboard. the only use for me is to get the image in screenshots folder
