### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Error.AccessDenied

### ISSUE THREAD

**Issue by kem-a** [elementary/screenshot#238]
### What Happened?

When taking a screenshot using app:

`GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: ScreenshotWindow is not allowed`

`GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Screenshot is not allowed`

`GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: SelectArea is not allowed`

### Steps to Reproduce

Take a screenshot

### Expected Behavior

No errors

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

Fedora 35 wayland
rpm from fedora repo
gnome 41

**Comment by tintou** [comment]
GNOME Shell recently restricted the possible users of the Screenshot interface to the very minimal. This issue should be fixed by supporting the portal (which is somewhat #140)

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/portals/pull/94 and https://github.com/elementary/screenshot/pull/284
