### ISSUE TITLE
Consider submitting elementary-screenshot also to upstream Debian?

### ISSUE THREAD

**Issue by marek-lach** [elementary/screenshot#242]
### Problem

Since Elementary is based on Debian, why not submit an elementary-screenshot package to upstream Debian as well, for those of us, for example, that use Debian on platforms other than x86 (like aarch64), but could still benefit from the app's particular functionality?

Thank you for considering,
Marek

### Proposal

Such an upstreaming effort'd make me much more appreciative of Elementary, even if I am not using it directly...

**Comment by jlnr** [comment]
This app is available as a flatpak, see link in the top right corner: https://appcenter.elementary.io/io.elementary.screenshot/

I have not tested it on Debian, though.

**Comment by danirabbit** [comment]
Yup gonna close since we make a Flatpak that can be installed anywhere and Debian could package this app if there was an interested maintainer :)
