### ISSUE TITLE
Screenshot won't save with slash in file name

### ISSUE THREAD

**Issue by PhilippeMorere** [elementary/screenshot#245]
### What Happened?

When saving a screenshot and putting a slash "/" in the filename, an error is thrown and the screenshot is not saved (and lost!).
A different behaviour of warning the user or removing the slash character would be better.

### Steps to Reproduce

1. Take a screenshot
2. save it with file name "hello/world"

### Expected Behavior

A different behaviour of warning the user or removing the slash character would be better.
Additionally, the screenshot should not be lost if this error happens.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
Thanks for finding this issue!

I think probably the proper thing to do would be to:
- [] use a ValidatedEntry
- [] display an error message when there's invalid characters
- [] make sure the save button is insensitive if the entry is marked invalid
