### ISSUE TITLE
Mouse cursor not included despite option

### ISSUE THREAD

**Issue by teamcons** [elementary/screenshot#286]
### What Happened?

I am taking screenshots and need to show elements or have my cursor present however the screenshot tool doe

### Steps to Reproduce

s not seem able to, on waylandrun screenshot tool
toggle on "include cursor"
set the timer
move cursor inside area

### Expected Behavior

cursor included in screenshot

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Duplicate of https://github.com/elementary/gala/issues/1737

**Comment by teamcons** [comment]
Why not planned ?

**Comment by jeremypw** [comment]
@teamcons  Isn't this fixed by https://github.com/elementary/gala/pull/2098?
