### ISSUE TITLE
Drag and Drop from save dialog

### ISSUE THREAD

**Issue by peteruithoven** [elementary/screenshot#29]
It would be great if after a screenshot was taken a notification would be shown with the image file, in such a way that it could be dragged from this notification into other applications. This would allow users to more easily upload the screenshot's to websites like github, or to a custom folder, or their favorite image editor. 

I didn't really come up with this myself, I heart that another Linux distro had this feature on the [Linux action show](https://www.youtube.com/playlist?list=PLUW3LUwQvegzv8xKCU44iZYS2BgXtzgom).

**Comment by peteruithoven** [comment]
I figured out I could use the [new](https://medium.com/elementaryos/loki-updates-for-april-c565b6024426#1f7d) `--clipboard` functionality, but this only seems available (currently) in the commandline and this means the file isn't stored to disk at all.

**Comment by uncertainquark** [comment]
+1 for this feature. KDE does this from Plasma 5.9 - https://www.kde.org/announcements/plasma-5.9.0.php

It would be very nice to have it on elementary as it seems like a very intuitive and convenient thing to do.

**Comment by danrabbit** [comment]
This is probably not an appropriate use of notifications, but we could implement drag and drop from the save dialog
