### ISSUE TITLE
Selection area sometimes is present on the screenshot

### ISSUE THREAD

**Issue by donadigo** [elementary/screenshot#50]
Sometimes the selection area itself is included in the screenshot itself making the screenshot dim. We should make sure that the area is hidden when we take the screenshot.

**Comment by purejava** [comment]
Is there a way to reproduce this @donadigo?
I made a couple of screenshots but could not manage to get a fail.

**Comment by donadigo** [comment]
Whoops, don't mind that accidental close / reopen.

**Comment by jlnr** [comment]
It just happened to me when reporting https://github.com/elementary/stylesheet/issues/313. I've retried maybe 20 times and had 4 screenshots that were affected. Image size is around ~3000x1000 pixels, Nvidia blob drivers, if that matters.
