### ISSUE TITLE
Automatically append scaling factor to filenames

### ISSUE THREAD

**Issue by cassidyjames** [elementary/screenshot#68]
It's a super common web convention to append `@2x` to any images that are at a 2x scaling factor. It might be handy to automatically append the scaling factor to images when it's >1. 

For example, this lets websites like Medium automatically set up the right sizing and scaling without any extra work from the user which is incredibly convenient.

**Comment by artemanufrij** [comment]
@cassidyjames in which environment variable is scale factor saved?

**Comment by danrabbit** [comment]
@artemanufrij You could probably use https://valadoc.org/gtk+-3.0/Gtk.Widget.scale_factor.html

**Comment by peteruithoven** [comment]
It looks like the scaling factor isn't added when using the command line tool.

**Comment by cassidyjames** [comment]
@peteruithoven I'm going to open a new issue since that's more specific.
