### ISSUE TITLE
Screenshot region is darker than it should

### ISSUE THREAD

**Issue by juanfgs** [elementary/screenshot#75]
So, here is a screenshot taken with Pantheon's Screenshot Tool : ![captura de pantalla de 2018-06-01 09-49-31](https://user-images.githubusercontent.com/507984/40841631-7e6a0d02-6581-11e8-8061-880eb614fcc6.png)

Similar screenshot taken by xfce4-screenshooter  ![captura de pantalla_2018-06-01_09-50-21](https://user-images.githubusercontent.com/507984/40841645-8ccee106-6581-11e8-8043-e46fb7690b36.png)

I belive that for some reason the darker overlay is actually appearing on the screenshot causing the screenshot to be darker than it should be.

**Comment by ryonakano** [comment]
Maybe same issue with #50 or [#211 of gala](https://github.com/elementary/gala/issues/211)

**Comment by danrabbit** [comment]
Closing as a duplicate of #50
