### ISSUE TITLE
Unify the name of app

### ISSUE THREAD

**Issue by ryonakano** [elementary/screenshot#85]
Which is the correct name, "Screenshot Tool" or "Screenshot"?

The name of this repo is screenshot-tool, and at the top of README.md the title is written "Screenshot Tool". RDNN name also says "io.elementary.screenshot-tool". However, [at 8 line in the appdata file](https://github.com/elementary/screenshot-tool/blob/e0ca30ab64cebeb46544cd64fe0f85eb347923d3/data/io.elementary.screenshot-tool.appdata.xml.in#L8) says Screenshot and [at 3 line in the desktop file](https://github.com/elementary/screenshot-tool/blob/e0ca30ab64cebeb46544cd64fe0f85eb347923d3/data/io.elementary.screenshot-tool.desktop.in#L3) also says Screenshot. Also the icon name is accessories-screenshot.

The name is not unified and this might make users confusing. I think we should unify the name of app to either notation.

**Comment by cassidyjames** [comment]
We should standardize on Screenshot. We don't name other things, "photos-app" for example.

**Comment by ryonakano** [comment]
If we rename the weblate url which is currently at https://l10n.elementary.io/projects/screenshot-tool/ we can finally close this issue :)

**Comment by tintou** [comment]
@ryonakano Done :tada:
